const fs=require('fs');const path='/Users/kodiecritzer/projects/poo-bears/index.html';let f=fs.readFileSync(path,'utf8');
const G=(n,dept,wf,q,a,u)=>({a,u:u||"",n,src:"wf",dept,wf,q});
const F=(n,a,u)=>({a,u:u||"",n,src:"farm",dept:"Freezer · Tiffin Farm"});
const P=(n,a,u)=>({a,u:u||"",n,src:"pantry",dept:"Pantry"});
const mR=f.match(/const R=\[[\s\S]*?\n\];/);let R;eval(mR[0].replace('const ',''));
const mS=f.match(/const S=\[[\s\S]*?\n\];/);let S;eval(mS[0].replace('const ',''));

// pairSauce for existing recipes
const PAIR={"korean-beef":"gochujang-sauce","beef-broccoli":"spicy-mayo","thai-basil":"nuoc-cham","teriyaki-salmon":"spicy-mayo","mongolian-beef":"gochujang-sauce","smash-burgers":"comeback-sauce","grilled-ny-strip":"chimichurri","beef-tacos":"cilantro-crema","chicken-fajitas":"cilantro-crema","honey-garlic-shrimp":"bang-bang","smash-burger-tacos":"chipotle-crema","sweet-potato-cottage-bowl":"cilantro-crema","crispy-rice-salmon":"spicy-mayo","marry-me-chicken":"garlic-herb-butter","pot-roast":"garlic-herb-butter","beef-chili":"cilantro-crema","orzo":"chimichurri","salmon":"spicy-mayo","teriyaki":"spicy-mayo","medi":"garlic-tahini","mississippi-pot-roast":"garlic-herb-butter","baked-feta-pasta":"marinara","grinder-sandwich":"comeback-sauce","cottage-cheese-alfredo":"marinara","hot-honey-chicken":"honey-mustard"};
R.forEach(r=>{ if(PAIR[r.id]) r.pairSauce=PAIR[r.id]; });

const NEWSAUCES=[
 {id:"comeback-sauce",img:"img/comeback-sauce.jpg",grad:"linear-gradient(150deg,#e8a05a,#c4663a)",title:"Comeback Sauce",cuisine:"Southern",makes:"about 1 cup",tags:[{t:"Southern",c:"w"},{t:"Dip",c:""}],pairs:["Fried chicken","Fries & onion rings","Burgers","Shrimp"],ing:["½ cup mayo","2 tbsp ketchup","1 tbsp chili sauce","1 tsp Dijon mustard","1 tsp Worcestershire","1 tsp hot sauce","1 clove garlic, grated","½ tsp smoked paprika","squeeze of lemon"],steps:["Whisk everything together until smooth.","Chill at least 30 minutes — it gets better as it sits.","Thin with a teaspoon of water if you want it pourable."],healthy:"A Mississippi classic. Sub Greek yogurt for half the mayo to lighten it."},
 {id:"garlic-herb-butter",img:"img/garlic-herb-butter.jpg",grad:"linear-gradient(150deg,#e0cf9a,#a89a5a)",title:"Garlic Herb Butter",cuisine:"French",makes:"about ½ cup",tags:[{t:"Finishing",c:""},{t:"5 ingredients",c:"g"}],pairs:["Steak","Crusty bread","Roasted potatoes","Seafood","Corn"],ing:["1 stick butter, softened","3 cloves garlic, grated","2 tbsp parsley, minced","1 tsp fresh thyme or rosemary","½ tsp flaky salt","squeeze of lemon"],steps:["Mash the softened butter with the garlic, herbs, salt and lemon until evenly combined.","Use right away on hot steak, bread or veg, or roll in parchment and chill into a log to slice.","Melts into anything hot — a little goes a long way."],healthy:"A finishing touch, not a base — a small pat does a lot of work."},
 {id:"marinara",img:"img/marinara.jpg",grad:"linear-gradient(150deg,#c0653a,#7a2c1a)",title:"20-Minute Marinara",cuisine:"Italian",makes:"about 3 cups",tags:[{t:"Italian",c:"w"},{t:"No added sugar",c:"g"}],pairs:["Chicken parm","Pasta","Gnocchi","Meatballs","Pizza"],ing:["28 oz crushed tomatoes","3 cloves garlic, sliced","3 tbsp olive oil","½ tsp red pepper flakes","1 tsp salt","handful fresh basil","pinch of sugar (optional)"],steps:["Warm the olive oil and gently sizzle the garlic and pepper flakes until fragrant — don't brown it.","Add the crushed tomatoes and salt. Simmer 20-25 minutes, stirring, until thickened and deepened.","Tear in fresh basil at the end. Taste — a pinch of sugar rounds out acidic tomatoes."],healthy:"Clean ingredients beat any jarred sauce, with no corn syrup or preservatives."},
 {id:"chipotle-crema",img:"img/chipotle-crema.jpg",grad:"linear-gradient(150deg,#d98a4e,#9c4a2a)",title:"Chipotle Crema",cuisine:"Mexican",makes:"about ¾ cup",tags:[{t:"Smoky",c:"w"},{t:"Greek yogurt option",c:"g"}],pairs:["Tacos","Burrito bowls","Birria","Fajitas","Grilled chicken"],ing:["½ cup Greek yogurt or sour cream","¼ cup mayo","1–2 chipotles in adobo + 1 tsp sauce","1 clove garlic","juice of ½ lime","pinch of salt"],steps:["Blend everything in the mini prep until smooth and pale orange.","Taste — add more chipotle for heat and smoke.","Chill until serving; thin with a little water to drizzle."],healthy:"Use all Greek yogurt for a lighter, protein-packed version."},
 {id:"honey-mustard",img:"img/honey-mustard.jpg",grad:"linear-gradient(150deg,#e0b84a,#a87e1a)",title:"Honey Mustard",cuisine:"American",makes:"about ¾ cup",tags:[{t:"Sweet-tangy",c:""},{t:"3 minutes",c:""}],pairs:["Chicken tenders","Pretzels","Salads","Sandwiches","Roasted veg"],ing:["¼ cup Dijon mustard","¼ cup honey","2 tbsp mayo or Greek yogurt","1 tsp apple cider vinegar","pinch of salt"],steps:["Whisk everything together until smooth and glossy.","Taste and balance — more honey for sweet, more Dijon for tang.","Keeps a couple weeks in the fridge."],healthy:"Use Greek yogurt instead of mayo to cut fat and add protein."},
];
S.push(...NEWSAUCES);

const NEW=[
 {id:"gigi-pasta",img:"img/gigi-pasta.jpg",grad:"linear-gradient(150deg,#e08a72,#9c3f4a)",title:"Spicy Vodka (Gigi) Pasta",cuisine:"Viral · Italian",app:"Skillet",equip:"Large skillet",prep:"10 min",cook:"25 min",base:5,kcal:560,pro:18,carb:70,fat:22,filt:["Quick"],tags:[{t:"Viral",c:"w"},{t:"Creamy",c:""},{t:"Pasta",c:""}],side:"Garlic bread and a simple arugula salad",pairSauce:"garlic-herb-butter",
  ing:[G("shallot","Produce","Organic Shallots","organic shallot",1,""),G("garlic","Produce","Organic Garlic","organic garlic",3,"cloves"),G("heavy cream","Dairy","365 Organic Heavy Cream","365 organic heavy cream",0.75,"cup"),G("parmesan, grated","Dairy","365 Parmigiano Reggiano","parmigiano reggiano",0.5,"cup"),G("fresh basil","Produce","Organic Basil","organic basil",0.25,"cup"),P("pasta (rigatoni or penne)",1,"lb"),P("tomato paste",0.25,"cup"),P("vodka (optional)",2,"tbsp"),P("olive oil, butter, red pepper flakes",1,"")],
  steps:["Bring a big pot of salted water to a boil for the pasta.","In a large skillet, warm olive oil and a knob of butter and soften the minced shallot and garlic, 3-4 minutes.","Stir in the tomato paste and red pepper flakes and cook 2-3 minutes until it darkens and goes jammy — this builds deep flavor.","Add the vodka if using and let it cook off 1 minute, then stir in the heavy cream until smooth and blush-pink.","Cook the pasta to al dente; reserve a cup of pasta water before draining.","Toss the pasta into the sauce with a splash of pasta water and the parmesan until glossy and coating every piece.","Finish with torn basil and more parmesan."],
  kids:"Creamy pink pasta — basically fancy mac. Skip the pepper flakes and it's mild.",
  tips:["Cook the tomato paste until it darkens — that's the flavor.","Reserve pasta water to emulsify the sauce.","Vodka is optional; it brightens but isn't essential."],
  note:"The viral Gigi Hadid pasta. Add cooked sausage or chicken to make it heartier."},

 {id:"birria-tacos",img:"img/birria-tacos.jpg",grad:"linear-gradient(150deg,#c0432a,#7a1f12)",title:"Birria Quesatacos",cuisine:"Viral · Mexican",app:"Crockpot",equip:"Crockpot + skillet",prep:"20 min",cook:"6 hr",base:6,kcal:620,pro:42,carb:34,fat:36,filt:["Beef"],tags:[{t:"Viral",c:"w"},{t:"Chuck roast",c:""},{t:"Crockpot",c:""}],side:"The consommé for dipping, plus lime and onion",pairSauce:"chipotle-crema",
  ing:[F("chuck roast (or short ribs)",3,"lb"),G("dried guajillo + ancho chiles","Canned · Beans","Dried Guajillo Chiles","dried guajillo chiles",4,""),G("white onion","Produce","Organic White Onion","organic white onion",1,""),G("garlic","Produce","Organic Garlic","organic garlic",5,"cloves"),G("corn tortillas","Bakery","365 Organic Corn Tortillas","corn tortillas",16,""),G("Oaxaca or mozzarella","Dairy","Shredded Mozzarella","shredded mozzarella",2,"cups"),G("cilantro + onion to top","Produce","Organic Cilantro","organic cilantro",1,"bunch"),P("beef broth",3,"cups"),P("cumin, oregano, cinnamon, bay",1,"")],
  steps:["Toast the dried chiles in a dry pan 30 seconds, then soak in hot water 10 minutes until soft. Blend with the garlic, half the onion, cumin, oregano, a small piece of cinnamon and a cup of broth into a smooth adobo.","Season the chuck roast with salt and add to the crockpot with the adobo and remaining broth.","Cook on LOW 6-8 hours until the beef shreds easily.","Shred the beef and skim the fat off the cooking liquid — that red liquid is your consommé for dipping.","For quesatacos: dip a tortilla in the consommé fat, lay it on a hot skillet, add cheese and beef, fold, and crisp both sides until golden.","Serve with cilantro, onion, lime and a cup of warm consommé for dipping."],
  kids:"Plain shredded beef with cheese in a lightly crisped tortilla — skip the dip and onion. They'll love the cheesy crunch.",
  tips:["Don't skip toasting the chiles — it deepens the whole sauce.","The skimmed consommé is the magic — dip every bite.","Short ribs or a mix make it even richer."],
  note:"The viral quesabirria. Big effort, big reward with a Tiffin chuck roast — makes a ton and freezes great."},

 {id:"french-onion-chicken",img:"img/french-onion-chicken.jpg",grad:"linear-gradient(150deg,#a06a3c,#4f2e16)",title:"French Onion Chicken",cuisine:"Viral · French",app:"Cast Iron",equip:"Oven-safe skillet",prep:"15 min",cook:"35 min",base:5,kcal:520,pro:44,carb:16,fat:30,filt:["Chicken"],tags:[{t:"Viral",c:"w"},{t:"Cheesy",c:""},{t:"Skillet",c:""}],side:"Mashed potatoes or crusty bread to mop the pan",pairSauce:"garlic-herb-butter",
  ing:[G("chicken breasts or thighs","Meat","365 Organic Boneless Skinless Chicken Thighs","365 organic boneless skinless chicken thighs",2.5,"lb"),G("yellow onions","Produce","365 Organic Yellow Onion","organic yellow onion",3,""),G("gruyere cheese","Dairy","Gruyere Cheese","gruyere cheese",1.5,"cups"),P("butter",3,"tbsp"),P("beef broth",1,"cup"),P("flour, thyme, Worcestershire",1,"")],
  steps:["Thinly slice the onions. Melt the butter in an oven-safe skillet and cook the onions low and slow, stirring often, 20-25 minutes until deeply caramelized and jammy. Patience here is everything.","Meanwhile season the chicken and, in a separate pan, sear it golden on both sides (it finishes in the oven). Set aside.","Stir a spoon of flour into the onions, then add the beef broth, a splash of Worcestershire and thyme; simmer into a glossy gravy.","Nestle the seared chicken into the onion gravy.","Pile gruyere over each piece and broil 3-4 minutes until bubbling and golden.","Serve with the onions and gravy spooned over."],
  kids:"Plain chicken with melty cheese — skip the onions on theirs if they're picky.",
  tips:["Caramelize the onions slowly — rushing them means no flavor.","Gruyere is classic but provolone or swiss work.","Use thighs for the juiciest result."],
  note:"Viral French onion soup, turned into a cheesy chicken dinner."},

 {id:"steak-bites",img:"img/steak-bites.jpg",grad:"linear-gradient(150deg,#a06a48,#4a2a1a)",title:"Garlic Butter Steak Bites",cuisine:"Viral · American",app:"Cast Iron",equip:"Cast iron skillet",prep:"10 min",cook:"10 min",base:4,kcal:460,pro:42,carb:3,fat:30,filt:["Beef","Quick"],tags:[{t:"Viral",c:"w"},{t:"Sirloin",c:""},{t:"Quick",c:""}],side:"Mashed potatoes or roasted veg",pairSauce:"garlic-herb-butter",
  ing:[F("sirloin or ribeye, 1-inch cubes",1.5,"lb"),P("butter",3,"tbsp"),G("garlic","Produce","Organic Garlic","organic garlic",4,"cloves"),G("fresh parsley","Produce","Organic Parsley","organic parsley",2,"tbsp"),P("olive oil, salt, coarse pepper",1,"")],
  steps:["Pat the steak cubes very dry and season generously with salt and coarse pepper. Dry meat means a good sear.","Get a cast iron skillet ripping hot with a little oil.","Add the steak in a single layer — don't crowd it — and sear undisturbed 1-2 minutes per side until browned but still pink inside. Work in batches if needed.","Lower the heat, add the butter and garlic, and toss the bites in the foaming garlic butter for 30-60 seconds.","Kill the heat, toss with parsley, and serve right away."],
  kids:"Tender little steak bites are perfect finger food — serve a few plain before the garlic butter.",
  tips:["Dry the meat and don't crowd the pan or it steams.","Pull them at medium-rare; they keep cooking off the heat.","A spoon of the Garlic Herb Butter (Sauces) takes them over the top."],
  note:"Viral 15-minute steak bites — a fast, fancy-feeling use of the cow's sirloin."},

 {id:"bang-bang-chicken",img:"img/bang-bang-chicken.jpg",grad:"linear-gradient(150deg,#e88a72,#c4506a)",title:"Bang Bang Chicken",cuisine:"Viral · Asian-American",app:"Air Fryer",equip:"Air fryer",prep:"15 min",cook:"16 min",base:5,kcal:520,pro:38,carb:40,fat:20,filt:["Chicken","Quick"],tags:[{t:"Viral",c:"w"},{t:"Spicy",c:"w"},{t:"Air fryer",c:""}],side:"Steamed rice or a crunchy slaw",pairSauce:"bang-bang",
  ing:[G("chicken thighs or breast","Meat","365 Organic Boneless Skinless Chicken Thighs","365 organic boneless skinless chicken thighs",2,"lb"),G("eggs","Dairy","Organic Eggs","organic eggs",2,""),P("panko breadcrumbs",1.5,"cups"),P("flour + cornstarch",1,""),P("mayo, sweet chili sauce, sriracha",1,"")],
  steps:["Cut the chicken into bite-size pieces. Set up a dredge: flour, then beaten egg, then panko.","Coat each piece — flour, egg, panko — pressing the panko on for a thick crust.","Spray well with oil and air fry at 400°F for 14-16 minutes, flipping halfway, until deep golden and 165°F.","Make the bang bang sauce: whisk ¼ cup mayo, 3 tbsp sweet chili and 1-2 tbsp sriracha (or grab it from the Sauces tab).","Toss the crispy chicken in the sauce, or drizzle to keep it crunchier.","Serve over rice or slaw with scallions."],
  kids:"Pull a few plain crispy nuggets before saucing — homemade chicken nuggets, basically.",
  tips:["Panko + oil spray gives deep-fried crunch without the oil.","Sauce at the last second so it stays crispy.","The Bang Bang sauce in the Sauces tab is the exact match."],
  note:"Crispy bang bang chicken, air-fried. Pairs with the Bang Bang sauce."},

 {id:"chicken-parm",img:"img/chicken-parm.jpg",grad:"linear-gradient(150deg,#c0653a,#6a2c1a)",title:"Chicken Parmesan",cuisine:"Italian-American",app:"Skillet",equip:"Skillet + oven",prep:"20 min",cook:"25 min",base:5,kcal:640,pro:46,carb:48,fat:28,filt:["Chicken"],tags:[{t:"Classic",c:""},{t:"Crispy",c:""},{t:"Cheesy",c:""}],side:"Spaghetti with marinara and a green salad",pairSauce:"marinara",
  ing:[G("chicken breasts (pounded thin)","Meat","Organic Chicken Breast","organic chicken breast",2.5,"lb"),G("eggs","Dairy","Organic Eggs","organic eggs",2,""),G("mozzarella","Dairy","Fresh Mozzarella","fresh mozzarella",2,"cups"),G("marinara or crushed tomatoes","Canned · Beans","Rao's Marinara","marinara sauce",24,"oz"),P("panko + grated parmesan",2,"cups"),P("flour, Italian seasoning",1,""),P("spaghetti",1,"lb")],
  steps:["Pound the chicken breasts to an even ½-inch thickness so they cook fast and stay juicy.","Set up a dredge: seasoned flour, beaten egg, then panko mixed with grated parmesan.","Coat each cutlet and pan-fry in a shallow layer of oil, 3-4 minutes per side, until deep golden and crisp. Drain.","Spoon marinara over each cutlet, top with mozzarella, and broil or bake until the cheese is melted and bubbling.","Meanwhile cook the spaghetti and toss with more marinara.","Serve the cutlets over the pasta with basil."],
  kids:"Crispy chicken + cheese + noodles — a guaranteed win. Serve sauce on the side if they're sauce-shy.",
  tips:["Pound the chicken thin for even, fast cooking.","Parmesan in the breading makes the crust extra savory.","Use the homemade Marinara from the Sauces tab."],
  note:"The crispy, cheesy classic. Make extra cutlets — they reheat great."},

 {id:"street-corn-chicken-bowl",img:"img/street-corn-chicken-bowl.jpg",grad:"linear-gradient(150deg,#caa14e,#6b4a1c)",title:"Street Corn Chicken Bowl",cuisine:"Viral · Mexican",app:"Grill",equip:"Grill or skillet",prep:"15 min",cook:"20 min",base:5,kcal:560,pro:40,carb:52,fat:20,filt:["Chicken"],tags:[{t:"Viral",c:"w"},{t:"Street corn",c:""},{t:"Bowl",c:""}],side:"It's a full bowl — add chips and guac",pairSauce:"chipotle-crema",
  ing:[G("chicken thighs","Meat","365 Organic Boneless Skinless Chicken Thighs","365 organic boneless skinless chicken thighs",2,"lb"),G("corn (4 ears or frozen)","Produce","Organic Corn","organic corn",4,""),G("cotija cheese","Dairy","Cotija Cheese","cotija cheese",0.5,"cup"),G("lime","Produce","Organic Lime","organic lime",2,""),G("cilantro","Produce","Organic Cilantro","organic cilantro",1,"bunch"),P("rice",2,"cups"),P("mayo, chili powder, tajín",1,""),P("cumin, chili powder, garlic (for chicken)",1,"")],
  steps:["Marinate the thighs in oil, lime, cumin, chili powder, garlic and salt for 15+ minutes.","Cook the rice. Grill or sear the chicken until charred and cooked through, then rest and slice.","Char the corn (grill, or in a hot dry skillet) until spotty and sweet.","Make the street-corn topping: toss the charred corn with a spoon of mayo, lime, chili powder, cotija and cilantro.","Build bowls: rice, sliced chicken, the elote corn.","Finish with more cotija, a squeeze of lime and a drizzle of chipotle crema."],
  kids:"Plain grilled chicken, plain corn and rice — deconstruct it. The charred corn is usually a hit.",
  tips:["Char the corn hard — that smoky sweetness is the whole point.","Cotija is traditional; feta works in a pinch.","Chipotle crema (Sauces) ties it all together."],
  note:"Viral street corn chicken bowl — smoky, tangy, fresh. Great for meal prep."},

 {id:"cajun-chicken-pasta",img:"img/cajun-chicken-pasta.jpg",grad:"linear-gradient(150deg,#b0552a,#5a2410)",title:"Cajun Chicken Pasta",cuisine:"Viral · Cajun",app:"Skillet",equip:"Large skillet",prep:"10 min",cook:"20 min",base:5,kcal:620,pro:40,carb:58,fat:26,filt:["Chicken","Quick"],tags:[{t:"Viral",c:"w"},{t:"Creamy",c:""},{t:"Spicy",c:"w"}],side:"Garlic bread and a green salad",pairSauce:"garlic-herb-butter",
  ing:[G("chicken breast or thighs","Meat","365 Organic Boneless Skinless Chicken Thighs","365 organic boneless skinless chicken thighs",1.5,"lb"),G("bell peppers","Produce","Organic Bell Peppers","organic bell peppers",2,""),G("garlic","Produce","Organic Garlic","organic garlic",3,"cloves"),G("heavy cream","Dairy","365 Organic Heavy Cream","365 organic heavy cream",1,"cup"),G("parmesan, grated","Dairy","365 Parmigiano Reggiano","parmigiano reggiano",0.5,"cup"),P("penne",1,"lb"),P("cajun seasoning, butter",1,"")],
  steps:["Toss the sliced chicken in a generous coat of cajun seasoning.","Sear the chicken in butter over medium-high until blackened and cooked through; remove.","In the same pan, sauté the sliced peppers and garlic until softened.","Pour in the heavy cream and a little more cajun seasoning; simmer 2-3 minutes, then stir in the parmesan until silky.","Cook the penne to al dente and toss it into the sauce with the chicken, loosening with pasta water.","Taste for salt and heat, and serve."],
  kids:"Go light on the cajun for theirs, or pull plain chicken + buttered noodles before saucing.",
  tips:["Blacken the chicken hard for that smoky cajun flavor.","Adjust the cajun seasoning — brands vary a lot in heat and salt.","Andouille sausage is a great add."],
  note:"Viral creamy cajun chicken pasta — spicy, rich, fast."},

 {id:"chili-garlic-noodles",img:"img/chili-garlic-noodles.jpg",grad:"linear-gradient(150deg,#c0432a,#6b1f12)",title:"Chili Garlic Noodles",cuisine:"Viral · Asian",app:"Wok",equip:"Wok or skillet",prep:"10 min",cook:"12 min",base:4,kcal:480,pro:14,carb:72,fat:16,filt:["Asian","Quick"],tags:[{t:"Viral",c:"w"},{t:"Noodles",c:""},{t:"Spicy",c:"w"}],side:"Add a fried egg or seared shrimp for protein",pairSauce:"gochujang-sauce",
  ing:[G("garlic","Produce","Organic Garlic","organic garlic",6,"cloves"),G("scallions","Produce","Organic Scallions","organic scallions",1,"bunch"),P("noodles (lo mein or spaghetti)",1,"lb"),P("soy sauce, chili crisp, sesame oil, brown sugar",1,"")],
  steps:["Boil the noodles to just-tender; reserve a little pasta water, then drain.","While they cook, mince a lot of garlic and slice the scallions, keeping whites and greens separate.","In a wok over medium heat, gently sizzle the garlic and scallion whites in oil + sesame oil until fragrant and just golden — don't burn it.","Stir in a few spoons of chili crisp, soy sauce and a pinch of brown sugar to make a glossy sauce.","Add the noodles and toss hard, adding a splash of pasta water so the sauce coats everything.","Finish with the scallion greens and extra chili crisp."],
  kids:"Buttered noodles with a little soy for them — skip the chili crisp. An egg they can stir in is a nice add.",
  tips:["Lots of garlic, gently toasted, is the backbone — don't rush it.","Chili crisp brings the crunch and heat; adjust to taste.","A fried egg or shrimp makes it a full meal."],
  note:"Viral Din Tai Fung-style garlic noodles — 15 minutes, pantry ingredients."},

 {id:"honey-garlic-salmon-bites",img:"img/honey-garlic-salmon-bites.jpg",grad:"linear-gradient(150deg,#e0875f,#9c3f3a)",title:"Honey Garlic Salmon Bites",cuisine:"Viral · Asian",app:"Air Fryer",equip:"Air fryer",prep:"10 min",cook:"10 min",base:5,kcal:460,pro:34,carb:32,fat:20,filt:["Asian","Seafood","Quick"],tags:[{t:"Viral",c:"w"},{t:"Seafood",c:""},{t:"Quick",c:""}],side:"Steamed rice and broccoli or edamame",pairSauce:"spicy-mayo",
  ing:[G("salmon, skin off, 1-inch cubes","Seafood","Wild-Caught Sockeye Salmon Fillet","wild sockeye salmon fillet",2,"lb"),G("garlic","Produce","Organic Garlic","organic garlic",4,"cloves"),G("scallions + sesame","Produce","Organic Scallions","organic scallions",1,"bunch"),P("honey, soy sauce, sriracha",1,""),P("cornstarch",1,"tbsp"),P("rice",2,"cups")],
  steps:["Pat the salmon cubes dry, toss lightly in cornstarch and a pinch of salt for a crisp edge.","Air fry at 400°F for 7-8 minutes until just cooked and lightly crisp.","Meanwhile simmer honey, soy, grated garlic and sriracha in a small pan 2-3 minutes until glossy and syrupy.","Toss the salmon bites in the honey garlic glaze, or drizzle to keep them crisp.","Serve over rice with scallions and sesame."],
  kids:"Pull a few plain salmon cubes + rice before glazing — soft, mild, easy to portion.",
  tips:["Cornstarch gives the cubes a crisp edge in the air fryer.","Don't overcook — salmon goes from perfect to dry fast.","A drizzle of spicy mayo (Sauces) is unreal on these."],
  note:"Viral honey garlic salmon bites — fast, crispy, sweet-savory."},

 {id:"philly-cheesesteak",img:"img/philly-cheesesteak.jpg",grad:"linear-gradient(150deg,#a06a48,#4a2a1a)",title:"Philly Cheesesteak",cuisine:"American",app:"Skillet",equip:"Cast iron or griddle",prep:"10 min",cook:"15 min",base:4,kcal:660,pro:40,carb:44,fat:36,filt:["Beef","Quick"],tags:[{t:"Classic",c:""},{t:"Cheesy",c:""},{t:"Quick",c:""}],side:"Chips or fries and a pickle",pairSauce:"comeback-sauce",
  ing:[F("ribeye or sirloin, very thinly sliced",1.5,"lb"),G("yellow onion","Produce","365 Organic Yellow Onion","organic yellow onion",1,""),G("green bell pepper","Produce","Organic Bell Peppers","organic bell pepper",1,""),G("provolone","Deli","Provolone Cheese","provolone cheese",8,"slices"),G("hoagie rolls","Bakery","Hoagie Rolls","hoagie rolls",4,""),P("butter, salt, pepper",1,"")],
  steps:["Slice the beef as thinly as you can (much easier while it's partly frozen).","Sauté the sliced onion and pepper in butter until soft and golden; push to one side.","Crank the heat, add the beef in a thin layer, and cook fast, chopping it up with the spatula, until just browned.","Mix the beef and veg together, lay provolone over the top, and let it melt into the meat.","Scoop into toasted hoagie rolls.","Serve hot — great with a swipe of comeback sauce."],
  kids:"Plain beef and melty cheese in a roll — skip the peppers and onions for them.",
  tips:["Slice the beef paper-thin while it's partly frozen.","High heat, quick cook — don't overcook the thin beef.","Provolone or Cheez Whiz are the authentic options."],
  note:"The classic Philly, a great use for a thin-sliced Tiffin ribeye or round."},

 {id:"sticky-asian-meatballs",img:"img/sticky-asian-meatballs.jpg",grad:"linear-gradient(150deg,#caa14e,#6b4a1c)",title:"Sticky Asian Meatballs",cuisine:"Viral · Asian",app:"Oven",equip:"Sheet pan + saucepan",prep:"15 min",cook:"20 min",base:5,kcal:480,pro:32,carb:38,fat:22,filt:["Beef"],tags:[{t:"Viral",c:"w"},{t:"Ground beef",c:""},{t:"Family",c:"g"}],side:"Steamed rice and broccoli",pairSauce:"gochujang-sauce",
  ing:[F("ground beef",1.5,"lb"),G("egg","Dairy","Organic Eggs","organic eggs",1,""),G("garlic + ginger","Produce","Organic Garlic","organic garlic",3,"cloves"),G("scallions + sesame","Produce","Organic Scallions","organic scallions",1,"bunch"),P("panko",0.5,"cup"),P("soy sauce, honey, hoisin, rice vinegar",1,""),P("cornstarch",1,"tbsp"),P("rice",2,"cups")],
  steps:["Heat the oven to 400°F. Mix the ground beef with the egg, panko, grated garlic, ginger, a splash of soy and salt. Don't overwork it.","Roll into 1.5-inch meatballs and bake on a lined sheet pan 15-18 minutes until browned and cooked through.","Meanwhile simmer soy, honey, hoisin and rice vinegar in a saucepan; stir in a cornstarch slurry and cook 1-2 minutes until thick and glossy.","Toss the baked meatballs in the sticky glaze to coat.","Serve over rice with scallions and sesame."],
  kids:"Meatballs are made for toddlers — pull a few plain before glazing, cut small.",
  tips:["Don't overmix the meat or the meatballs get dense.","Bake, don't fry — easier and less mess.","A great use of the cow's ground beef; doubles for a crowd."],
  note:"Viral sticky asian meatballs — sweet, savory, kid-approved."},

 {id:"sheet-pan-gnocchi",img:"img/sheet-pan-gnocchi.jpg",grad:"linear-gradient(150deg,#8a9a3e,#3f5020)",title:"Crispy Sheet-Pan Gnocchi",cuisine:"Viral · Italian",app:"Oven",equip:"Sheet pan",prep:"10 min",cook:"30 min",base:4,kcal:440,pro:12,carb:64,fat:16,filt:["Quick"],tags:[{t:"Viral",c:"w"},{t:"Vegetarian",c:"g"},{t:"Sheet pan",c:""}],side:"A green salad, or add sausage/chicken for protein",pairSauce:"marinara",
  ing:[G("cherry tomatoes","Produce","Organic Cherry Tomatoes","organic cherry tomatoes",1,"pint"),G("zucchini","Produce","Organic Zucchini","organic zucchini",1,""),G("bell pepper","Produce","Organic Bell Peppers","organic bell pepper",1,""),G("red onion","Produce","Organic Red Onion","organic red onion",1,""),G("parmesan + basil","Dairy","365 Parmigiano Reggiano","parmigiano reggiano",0.5,"cup"),P("shelf-stable potato gnocchi",1,"lb"),P("olive oil, Italian seasoning, garlic",1,"")],
  steps:["Heat the oven to 425°F. On a sheet pan, toss the UNCOOKED gnocchi with the chopped zucchini, pepper, red onion, cherry tomatoes, olive oil, garlic, Italian seasoning and salt.","Spread into a single layer — crowding steams instead of crisps.","Roast 25-30 minutes, tossing once, until the gnocchi are golden and crisp-edged and the tomatoes burst.","Smash some of the burst tomatoes to make a light sauce that coats everything.","Finish with parmesan and torn basil."],
  kids:"Crispy little gnocchi are fun finger food — serve their veg on the side to dip in marinara.",
  tips:["Use the gnocchi straight from the package — no boiling.","Single layer means crispy, not mushy.","Add sausage or chickpeas to make it filling."],
  note:"Viral crispy sheet-pan gnocchi — one pan, no boiling, all veg."},

 {id:"coconut-curry-chicken",img:"img/coconut-curry-chicken.jpg",grad:"linear-gradient(150deg,#caa15e,#7a4a1e)",title:"Coconut Curry Chicken",cuisine:"Thai",app:"Skillet",equip:"Large skillet or pot",prep:"15 min",cook:"25 min",base:5,kcal:540,pro:36,carb:46,fat:24,filt:["Asian","Chicken"],tags:[{t:"Comfort",c:""},{t:"Creamy",c:""},{t:"Cozy",c:"g"}],side:"Jasmine rice and lime",pairSauce:"peanut-sauce",
  ing:[G("chicken thighs","Meat","365 Organic Boneless Skinless Chicken Thighs","365 organic boneless skinless chicken thighs",2,"lb"),G("bell pepper","Produce","Organic Bell Peppers","organic bell pepper",1,""),G("onion","Produce","365 Organic Yellow Onion","organic yellow onion",1,""),G("garlic + ginger","Produce","Organic Garlic","organic garlic",3,"cloves"),G("lime + cilantro","Produce","Organic Lime","organic lime",2,""),P("red curry paste",3,"tbsp"),P("coconut milk (2 cans)",27,"oz"),P("fish sauce, brown sugar",1,""),P("jasmine rice",2,"cups")],
  steps:["Start the rice. Cut the chicken into bite-size pieces.","In a large skillet, fry the red curry paste in a little oil for 1 minute until fragrant, then add the garlic, ginger, onion and pepper and cook 3-4 minutes.","Add the chicken and brown lightly.","Pour in the coconut milk with a splash of fish sauce and a pinch of brown sugar. Simmer 15 minutes until the chicken is cooked and the sauce thickens slightly.","Finish with lime juice and taste — balance salty, sweet and sour.","Serve over jasmine rice with cilantro and lime."],
  kids:"Mild and creamy — go easy on the curry paste for theirs. Plenty of soft chicken and rice.",
  tips:["Fry the curry paste first to wake up the flavor.","Adjust curry paste to your heat tolerance — brands vary.","Add anything: snap peas, spinach, sweet potato."],
  note:"A cozy Thai red coconut curry — one pot, endlessly adaptable."},

 {id:"carne-asada",img:"img/carne-asada.jpg",grad:"linear-gradient(150deg,#9a6a3a,#4a2a16)",title:"Carne Asada",cuisine:"Mexican · Grill",app:"Grill",equip:"Weber grill",prep:"30 min",cook:"12 min",base:6,kcal:420,pro:40,carb:6,fat:24,filt:["Beef","Quick"],tags:[{t:"Grill",c:""},{t:"Flank / skirt",c:""},{t:"Tiffin cut",c:"g"}],side:"Warm tortillas, rice, beans, guac — taco night",pairSauce:"chimichurri",
  ing:[F("flank or skirt steak",2,"lb"),G("limes + orange","Produce","Organic Lime","organic lime",3,""),G("garlic","Produce","Organic Garlic","organic garlic",5,"cloves"),G("cilantro","Produce","Organic Cilantro","organic cilantro",1,"bunch"),P("olive oil, cumin, chili powder, salt",1,"")],
  steps:["Make the marinade: whisk lime + orange juice, minced garlic, chopped cilantro, olive oil, cumin, chili powder and salt.","Marinate the flank or skirt steak 30 minutes to a few hours (don't go past 8 hours or the acid mushes it).","Get the Weber screaming hot. Grill the steak 3-4 minutes per side for medium-rare, until well charred.","Rest 8-10 minutes — non-negotiable for a juicy steak.","Slice thinly AGAINST the grain (critical for flank and skirt tenderness).","Pile into warm tortillas with onion, cilantro, lime and a spoon of chimichurri."],
  kids:"Thin-sliced asada is tender and mild — make them a simple taco or quesadilla with cheese.",
  tips:["Slice against the grain or it'll be chewy.","Don't over-marinate — past 8 hours the acid breaks the meat down too far.","Rest before slicing to keep the juices in."],
  note:"Carne asada on the Weber — the best taco-night use of a Tiffin flank or skirt. Killer with chimichurri."},
];
R.push(...NEW);

const outR='const R=[\n '+R.map(o=>JSON.stringify(o)).join(',\n ')+'\n];';
const outS='const S=[\n '+S.map(o=>JSON.stringify(o)).join(',\n ')+'\n];';
f=f.replace(mR[0],outR).replace(mS[0],outS);
fs.writeFileSync(path,f);
console.log('recipes:',R.length,'| sauces:',S.length,'| recipes w/ pairSauce:',R.filter(r=>r.pairSauce).length);
